name: Windows RDP (Pinggy)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 360
    steps:
      - name: RDP ve Kullanıcı Ayarları
        run: |
          # Şifre kurallarına uyması için Admin1234! yapıldı
          net user runneradmin Admin1234!
          
          # RDP'yi etkinleştir
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          
          # NLA devre dışı bırak (bağlantı sorunlarını çözer)
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 0

      - name: Pinggy ile Tünel Başlat
        run: |
          ssh -o StrictHostKeyChecking=no -p 443 -R0:localhost:3389 a.pinggy.io
